### ISSUE TITLE
private has to changed to protected

### ISSUE THREAD

**Issue by avandalen** [adafruit/Adafruit_ZeroTimer#1]
I have made a timer library for the SAMD21, see here:
http://www.avdweb.nl/arduino/libraries/samd21-timer.html
The base class is the Adafruit_ZeroTimer and therefore private has to changed to protected in the header.
Can this be carried out?

**Comment by ladyada** [comment]
can you submit a pull req and ill merge it asap?

**Comment by avandalen** [comment]
yes I will do

**Comment by avandalen** [comment]
Hi

I have done it, but I have no experience in doing this at github, I hope it is done well

Albert
