### ISSUE TITLE
Changing period of timer with callback

### ISSUE THREAD

**Issue by soulsbysynths** [adafruit/Adafruit_ZeroTimer#11]
Following on from this forum thread: [https://forums.adafruit.com/viewtopic.php?f=25&t=140598&p=724596#p724596](url)

I can successfully set up a timer with a callback as shown in timers_callback.ino

However once running I need to:

- Stop the timer

- Change the period

- Restart the timer using the callback

Unfortunately after restarting the timer, the callback is no-longer called.

Here's my code:
```C++
void AtxC::sequencerBpmChanged(uint_fast16_t bpm)
{
   seqTimer_.enable(false);  //tried with this line in and out
   seqTimer_.setCallback(false, TC_CALLBACK_CC_CHANNEL0, AtxC::pollSequencerCallback);  //tried with this line in and out
   uint32_t periodCounter = ((uint32_t)F_CPU * 60) / ((bpm * AtxCSequencer::CLKS_PER_QUARTER_NOTE)<<2);  //30bpm = 1000000  300bpm = 400000
   periodCounter >>= 3;  //default TC_CLOCK_PRESCALER_DIV8
   if (periodCounter>UINT16_MAX)
   {
      periodCounter >>= 1;
      seqTimer_.configure(TC_CLOCK_PRESCALER_DIV16,TC_COUNTER_SIZE_16BIT,TC_WAVE_GENERATION_MATCH_FREQ);
      seqTimer_.setPeriodMatch(periodCounter, periodCounter >> 1); // 1 match, channel 0
   }
   else
   {
      seqTimer_.configure(TC_CLOCK_PRESCALER_DIV8,TC_COUNTER_SIZE_16BIT,TC_WAVE_GENERATION_MATCH_FREQ);
      seqTimer_.setPeriodMatch(periodCounter, periodCounter >> 1); // 1 match, channel 0
   }
   seqTimer_.setCallback(true, TC_CALLBACK_CC_CHANNEL0, AtxC::pollSequencerCallback);  //tried with this line in and out
   seqTimer_.enable(true); //tried with this line in and out
}
```

As you can see, I have tried altering the period with and without disabling the timer/callback first. Unfortunately nothing works.

**Comment by ladyada** [comment]
could very well be, we don't use that functionality. if you can figure out how to fix it we would appreciate a PR - we don't currently have a maintainer & it wasn't designed/documented/tested for customer use!

**Comment by soulsbysynths** [comment]
OK no probs - thanks for letting me know.  I'll do some digging through the libraries and see if I can work it out.  If I do, I'll let you know!

**Comment by ladyada** [comment]
you can now call setCallback repeatedly like so

```
  zerotimer.enable(false);
  zerotimer.configure(prescaler, // prescaler
		      TC_COUNTER_SIZE_16BIT,   // bit width of timer/counter
		      TC_WAVE_GENERATION_MATCH_PWM // frequency or PWM mode
		      );

  zerotimer.setCompare(0, compare);
  zerotimer.setCallback(true, TC_CALLBACK_CC_CHANNEL0, callback);
  zerotimer.enable(true);
```

**Comment by trademark-online** [comment]
Thanks so much for this update!  I never managed to work out the issue myself, so I was using a real bodge of setting a very high timer frequency and dividing it down to the required rate.  
It'll be much better now that I can set the exact frequency each time.

**Comment by soulsbysynths** [comment]
Thanks so much for this update! I never managed to work out the issue myself, so I was using a real bodge of setting a very high timer frequency and dividing it down to the required rate.
It'll be much better now that I can set the exact frequency each time.
