### ISSUE TITLE
Sleep ?

### ISSUE THREAD

**Issue by aessig** [adafruit/Adafruit_ZeroTimer#12]
- Arduino board:  MKRZero

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.10

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): Do you think it would be possible to have the capabilities to put the uC in deep sleep? Similar to what RTCZero provide with **standbyMode**. Trying to use the following would make the interrupt never happened. 

```
void RTCZero::standbyMode()
{
  // Entering standby mode when connected
  // via the native USB port causes issues.
  SCB->SCR |= SCB_SCR_SLEEPDEEP_Msk;
  __DSB();
  __WFI();
}
```

Thanks :)

**Comment by ladyada** [comment]
you could check https://github.com/adafruit/Adafruit_SleepyDog
