### ISSUE TITLE
Lying comments about gclk selection

### ISSUE THREAD

**Issue by WestfW** [adafruit/Adafruit_ZeroTimer#16]
The code that sets the GCLK for the timer has a comment that is incorrect (copied from analogWrite() code?)
It says "use clock generator 0" when it's quite clearly setting GCLK1...

```
#if defined(__SAMD51__)
  GCLK->PCHCTRL[inst_gclk_id[instance]].reg =
      GCLK_PCHCTRL_GEN_GCLK1_Val |
      (1 << GCLK_PCHCTRL_CHEN_Pos); // use clock generator 0
#else
```

**Comment by ladyada** [comment]
you can re-open with a more positive title
