### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by gjt211** [adafruit/Adafruit_ZeroTimer#4]
- Arduino board:  **Sparkfun SAMD21 Mini Breakout**

- Arduino IDE version 1.8.3

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**
```
#include <Arduino.h>
#include "Adafruit_ZeroTimer.h"

const int BLUE_LED = 13; // Blue "stat" LED on pin 13

void setup() 
{
  pinMode(BLUE_LED, OUTPUT);
}

void loop() 
{
}
```

Click compile and the result is as follows...
```
In file included from /Users/user1/Library/Mobile Documents/com~apple~CloudDocs/Arduino/SFSAMD21_01/SFSAMD21_01.ino:3:0:
/Users/user1/Library/Mobile Documents/com~apple~CloudDocs/Arduino/libraries/Adafruit_ZeroTimer-master/Adafruit_ZeroTimer.h:11:16: fatal error: tc.h: No such file or directory
 #include "tc.h"
                ^
compilation terminated.
exit status 1
Error compiling for board SparkFun SAMD21 Mini Breakout.
```

So where is the file `tc.h` meant to be?
Why would the library need it if it was not included?
Are there any instructions?

**Comment by tuna-f1sh** [comment]
I believe you also need the [Adafruit_ASFcore library](https://github.com/adafruit/Adafruit_ASFcore) as this library uses lots of the Atmel Software Framework (ASF) components. It's how I fixed it at least.

You don't even need to include the Adafruit-ASFcore in your sketch, the Arduino pre-parser will pull it in for you if you have the library in your libraries folder - I guess that is why it is not present in the examples.

**Comment by ladyada** [comment]
we gutted out ASFcore - try now, note the code has changed so check examples!
