### ISSUE TITLE
Adafruit_ZeroTimer::setTop() declared but not defined

### ISSUE THREAD

**Issue by jpjazz** [adafruit/Adafruit_ZeroTimer#8]
- Arduino board:  Feather M4 Express (or any SAMD board)

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.5

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**

I just noticed that the Adafruit_ZeroTimer::setTop() member function is declared in Adafruit_ZeroTimer.h, but apparently not defined in Adafruit_ZeroTimer.cpp. I think this function would be useful for a project I'm working on.

**Comment by ladyada** [comment]
hiya, we removed to avoid confusion.
